project:
  type: website

website:
  title: "ISSS608-VAAGroup5"
  navbar:
    left:
      - href: home.qmd
        text: Home
      - href: proposal.qmd
        text: "Project Proposal"

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

