project:
  type: website

website:
  title: "ISSS608-VAAGroup5"
  navbar:
    right:
      - href: proposal.qmd
        text: "Project Proposal"
      - href: https://group5vaaapr23.shinyapps.io/shinyapp/
        text: "RShiny App"
      - href: Group5_Userguide.pdf
        text: "User Guide"
      - href: Group5_Poster.jpg
        text: "Poster"
      

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

